# Generated by Django 5.2.7 on 2025-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(unique=True)),
                ("t_max", models.FloatField()),
                ("t_mean", models.FloatField()),
                ("t_min", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
