# Generated by Django 5.2.7 on 2025-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
