# Generated by Django 5.2.7 on 2025-10-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_weatherdata_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="city",
            field=models.CharField(default="Budapest", max_length=100),
            preserve_default=False,
        ),
    ]
